### ISSUE TITLE
Mapas de Karnaught

### ISSUE THREAD

**Issue by Alondra-oss** [SistemasTecTlaxiaco/actividad-12-ejercicios-de-mapas-de-karnaught-team-sael-1as#1]
[(MAPAS DE KARNAUGHT)Practica.pdf](https://github.com/user-attachments/files/18044448/MAPAS.DE.KARNAUGHT.Practica.pdf)

**Comment by Victor-noe12** [comment]
Portada:25/25
Procedimiento/Desarrollo:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
